version: '1'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/ecommerce-app
      - /usr/src/ecommerce-app/node_modules

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
